import { Job } from "@/types/job";

const jobs: Job[] = [
  {
    id: "1",
    role: "Telecommunications Equipment Technician",
    company_name: "TeleComm Services Ltd",
    company_logo: "/images/company-logo.jpg",
    tags: [
      { name: "Full-time", color: "flutter" },
      { name: "On-site", color: "mobile" },
      { name: "Telecommunications", color: "ios" },
      { name: "Equipment Repair", color: "android" },
    ],
    full_description:
      "TeleComm Services Ltd is seeking a Telecommunications Equipment Technician to diagnose, repair, and maintain telecommunications equipment. This on-site position requires 7 months to less than 1 year of experience and a secondary (high) school graduation certificate. Work must be completed at the physical location with no remote work options.",
    responsibilities: [
      "Diagnose and locate equipment faults, and adjust, replace or repair telecommunications equipment",
      "Inspect operation of telecommunications equipment to ensure proper functionality",
      "Install, arrange, remove and maintain telephone equipment, wiring and associated hardware",
      "Repair or replace defective telephone equipment and components",
      "Analyze test results and adjust, change or repair switching system, network, associated equipment and software",
      "Complete and maintain accurate test and service reports",
      "Determine nature, cause and location of trouble in telecommunications systems",
      "Determine work assignments and prioritize repair tasks",
      "Perform routine maintenance on telecommunications infrastructure",
      "Ensure compliance with safety protocols and industry standards",
      "Coordinate with team members on complex repair projects",
      "Maintain inventory of spare parts and equipment",
    ],
    qualifications: [
      "7 months to less than 1 year of experience in telecommunications equipment repair",
      "Secondary (high) school graduation certificate required",
      "Strong attention to detail and manual dexterity",
      "Knowledge of telecommunications equipment and systems",
      "Experience with diagnostic tools and testing equipment",
      "Ability to read and interpret technical diagrams and schematics",
      "Understanding of electrical and electronic principles",
      "Client focus with excellent customer service skills",
      "Flexibility and adaptability to changing work requirements",
      "Reliability and dependability in completing assignments",
      "Physical capability to work with equipment and wiring",
      "Ability to work on-site with no remote work options",
      "Problem-solving skills for troubleshooting equipment issues",
      "Proficiency in English",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/45007726",
  },
  {
    id: "2",
    role: "Telecommunications Line Technician",
    company_name: "ConnectTel Communications",
    company_logo: "/images/mobile-tech.jpg",
    tags: [
      { name: "Full-time", color: "flutter" },
      { name: "On-site", color: "mobile" },
      { name: "Outdoors", color: "dart" },
      { name: "Installation", color: "ios" },
    ],
    full_description:
      "ConnectTel Communications is seeking an experienced Telecommunications Line Technician for installation, maintenance, and repair work in both urban and rural areas. This physically demanding position requires working outdoors and at heights with no remote work options. We require 3 years to less than 5 years of experience with no formal education requirements.",
    responsibilities: [
      "Install and maintain aerial and underground telephone equipment",
      "Install trunking systems, circuits and equipment",
      "Climb and work aloft on poles, ladders or other support structures",
      "Perform maintenance and repair of telecommunications infrastructure",
      "Work in various weather conditions and outdoor environments",
      "Ensure safety protocols are followed when working at heights",
      "Troubleshoot and diagnose equipment issues",
      "Maintain accurate records of work performed",
      "Respond to service calls in both urban and rural areas",
      "Coordinate with team members and supervisors on project timelines",
    ],
    qualifications: [
      "3 years to less than 5 years of experience in telecommunications",
      "No degree, certificate or diploma required",
      "Valid driver's licence required for transportation to work sites",
      "Ability to work in a fast-paced environment with attention to detail",
      "Physical capability to perform demanding tasks and work at heights",
      "Must provide own steel-toed safety boots and tools/equipment",
      "Flexibility and adaptability to changing work conditions",
      "Strong judgement and decision-making skills",
      "Highly organized and reliable work approach",
      "Ability to work outdoors in various weather conditions",
      "Experience with aerial and underground telecommunications equipment",
      "Proficiency in English",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/45007710",
  },
  {
    id: "3",
    role: "Audio-Visual Technician",
    company_name: "ProMedia Productions",
    company_logo: "/images/creative-studios.jpg",
    tags: [
      { name: "Full-time", color: "flutter" },
      { name: "Travel Required", color: "mobile" },
      { name: "Live Events", color: "ios" },
      { name: "Technician", color: "android" },
    ],
    full_description:
      "ProMedia Productions is seeking an experienced Audio-Visual Technician for live concert production and multimedia presentations. This role requires frequent travel to various urban locations and willingness to relocate. We require 3 years to less than 5 years of experience and a secondary (high) school graduation certificate.",
    responsibilities: [
      "Operate electronic equipment that transmits video conferencing or multimedia presentations",
      "Set up equipment for scheduled production events",
      "Supervise other technical staff during live events",
      "Operate mixing, dubbing, editing machinery and equipment",
      "Operate audio consoles or computers, tape machines, microphones and sound processing equipment at concerts and live events",
      "Operate audio-visual or electronic equipment for various productions",
      "Ensure equipment is properly calibrated and functioning before events",
      "Troubleshoot technical issues during live productions",
      "Coordinate with production teams to meet tight deadlines",
      "Maintain and transport equipment to various locations",
      "Provide technical support for multimedia presentations",
      "Work under pressure in fast-paced live event environments",
    ],
    qualifications: [
      "3 years to less than 5 years of experience in audio-visual production",
      "Secondary (high) school graduation certificate required",
      "Experience in live concert production preferred",
      "Proficiency with MS Windows operating systems",
      "Valid driver's licence required for travel between locations",
      "Willingness to travel frequently and relocate as needed",
      "Sound discrimination abilities and attention to detail",
      "Ability to work in fast-paced environments under pressure",
      "Physical capability for combination of sitting, standing, and walking",
      "Client focus with excellent interpersonal skills",
      "Excellent oral and written communication skills",
      "Flexibility and initiative in problem-solving",
      "Strong judgement and organizational skills",
      "Team player mentality with supervisory capabilities",
      "Proficiency in English",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/45004236",
  },
  {
    id: "4",
    role: "Network Administrator",
    company_name: "TechNet Solutions",
    company_logo: "/images/serverside.jpg",
    tags: [
      { name: "Full-time", color: "flutter" },
      { name: "On-site", color: "mobile" },
      { name: "Networks", color: "ios" },
      { name: "Edmonton", color: "android" },
    ],
    full_description:
      "TechNet Solutions is seeking a dedicated Network Administrator to coordinate and maintain our computer networks and systems. This on-site position requires 1 year to less than 2 years of experience and College/CEGEP education. Work must be completed at the physical location with no remote work options.",
    responsibilities: [
      "Coordinate access and use of computer networks",
      "Maintain, troubleshoot and administer the use of local area networks (LANs), wide area networks (WANs), mainframe networks and computer workstations and peripheral equipment",
      "Monitor the performance of computer systems and networks",
      "Evaluate and install computer hardware, networking software and operating system software",
      "Provide problem-solving services to network users",
      "Implement data, software and hardware security procedures",
      "Perform routine network start up and close down and maintain control records",
      "Perform data backups and disaster recovery operations",
      "Set up local area networks and connections to the Internet",
      "Implement network traffic and security monitoring software, and optimize server performance",
      "Perform Web-server backup and recovery operations",
      "Troubleshoot network connectivity issues and provide technical support",
      "Maintain network documentation and configuration records",
      "Ensure compliance with security policies and procedures",
    ],
    qualifications: [
      "1 year to less than 2 years of experience in network administration",
      "College/CEGEP education in computer science, networking, or related field",
      "Experience with virtualization technologies",
      "Knowledge of device drivers and networking hardware/software",
      "Proficiency with intranet and internet technologies",
      "Experience with servers and security software",
      "Proficiency in data analysis software, MS Office, and MS Windows",
      "Ability to work in fast-paced environment under pressure",
      "Capability to meet tight deadlines and handle repetitive tasks",
      "Strong attention to detail and accuracy",
      "Client focus with efficient interpersonal skills",
      "Excellent oral and written communication skills",
      "Initiative and organizational skills",
      "Team player mentality",
      "Ability to work on-site with no remote work options",
      "Proficiency in English",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/45007699",
  },
  {
    id: "5",
    role: "Web Developer",
    company_name: "Digital Solutions Inc",
    company_logo: "/images/cloudnative.jpg",
    tags: [
      { name: "Full-time", color: "flutter" },
      { name: "On-site", color: "mobile" },
      { name: "Web Development", color: "ios" },
      { name: "Edmonton", color: "android" },
    ],
    full_description:
      "Digital Solutions Inc is seeking a Web Developer to develop website architecture and maintain web applications. This on-site position requires 7 months to less than 1 year of experience and College/CEGEP education. Work must be completed at the physical location with no remote work options.",
    responsibilities: [
      "Develop website architecture and design frameworks",
      "Write, modify and test website related code",
      "Write, modify, integrate and test software code",
      "Maintain existing computer programs by making modifications as required",
      "Prepare reports, manuals and other documentation on the status, operation and maintenance of software",
      "Create and optimize content for Website using a variety of graphics, database, animation and other software",
      "Research and evaluate a variety of software products",
      "Conduct tests and perform security and quality controls",
      "Collaborate with design and development teams on web projects",
      "Optimize websites for maximum speed and scalability",
      "Ensure cross-browser compatibility and responsive design",
      "Debug and troubleshoot website issues and bugs",
    ],
    qualifications: [
      "7 months to less than 1 year of experience in web development",
      "College/CEGEP education in computer science, web development, or related field",
      "Proficiency in HTML, CSS, and JavaScript",
      "Experience with website architecture and design patterns",
      "Knowledge of graphics, database, and animation software",
      "Understanding of software testing and quality control processes",
      "Experience with security best practices for web applications",
      "Ability to write clear technical documentation",
      "Strong problem-solving and debugging skills",
      "Knowledge of responsive design and cross-browser compatibility",
      "Familiarity with version control systems",
      "Ability to work on-site with no remote work options",
      "Excellent attention to detail and code quality",
      "Proficiency in English",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/45007735",
  },
];

export default jobs;
