import { Job } from "@/types/job";

const jobs: Job[] = [
  {
    id: "1",
    role: "Café Manager",
    company_name: "Second Cup",
    company_logo: "/images/company-logo.jpg",
    location: "Edmonton, AB",
    tags: [
      { name: "Part-time", color: "flutter" },
      { name: "On-site", color: "mobile" },
      { name: "Edmonton, AB", color: "ios" },
      { name: "Management", color: "android" },
    ],
    full_description:
      "Second Cup is seeking a dedicated Café Manager for our Edmonton location. This on-site position offers $36.60-$37.60 hourly (negotiable) for 30 hours per week. We require 2 years to less than 3 years of experience and a College/CEGEP certificate or diploma from a 3 months to 1 year program. Work must be completed at the physical location with no remote work options.",
    responsibilities: [
      "Monitor revenues to determine labour cost and optimize financial performance",
      "Monitor staff performance and provide feedback for improvement",
      "Plan and organize daily operations to ensure smooth café functionality",
      "Recruit staff and conduct hiring processes for café positions",
      "Set staff work schedules to meet operational needs",
      "Train staff on café procedures, customer service, and product knowledge",
      "Determine type of services to be offered and implement operational procedures",
      "Ensure health and safety regulations are followed at all times",
      "Negotiate arrangements with suppliers for food and other supplies",
      "Negotiate with clients for catering or use of facilities",
      "Address customers' complaints or concerns in a professional manner",
      "Maintain inventory levels and order supplies as needed",
      "Ensure compliance with Second Cup brand standards and policies",
      "Manage cash handling and daily financial reporting",
    ],
    qualifications: [
      "2 years to less than 3 years of experience in management or supervisory roles",
      "College, CEGEP or other non-university certificate or diploma from a program of 3 months to less than 1 year",
      "Experience in food service or retail management preferred",
      "Strong understanding of labour cost management and revenue monitoring",
      "Proven ability to recruit, train, and manage staff",
      "Knowledge of health and safety regulations in food service",
      "Experience with supplier negotiations and inventory management",
      "Excellent customer service and complaint resolution skills",
      "Ability to work in a fast-paced environment",
      "Strong ability to work independently and make decisions",
      "Efficient interpersonal skills for team management",
      "Team player mentality with leadership capabilities",
      "Ability to work on-site with no remote work options",
      "Proficiency in English",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/44998136",
  },
  {
    id: "2",
    role: "Administrative Assistant",
    company_name: "Westrich Construction Alberta Ltd",
    company_logo: "/images/mobile-tech.jpg",
    location: "Edmonton, AB",
    tags: [
      { name: "Full-time", color: "flutter" },
      { name: "On-site", color: "mobile" },
      { name: "Edmonton, AB", color: "dart" },
      { name: "Administration", color: "ios" },
    ],
    full_description:
      "Westrich Construction Alberta Ltd is seeking an Administrative Assistant for our Edmonton office (T5J 0L1). This permanent, full-time on-site position offers $25.64-$27.64 hourly (negotiable) for 30 hours per week starting as soon as possible. We require 1 to less than 7 months of experience and a secondary (high) school graduation certificate. Work must be completed at the physical location with no remote work options.",
    responsibilities: [
      "Coordinate the flow of information within the team",
      "Open and distribute mail and other materials to appropriate recipients",
      "Record and prepare minutes of meetings, seminars and conferences",
      "Schedule and confirm appointments for management and team members",
      "Answer telephone and relay telephone calls and messages professionally",
      "Compile data, statistics and other information for reporting purposes",
      "Order office supplies and maintain inventory levels",
      "Arrange travel, related itineraries and make reservations",
      "Greet people and direct them to contacts or service areas",
      "Set up and maintain manual and computerized information filing systems",
      "Type and proofread correspondence, forms and other documents",
      "Perform data entry tasks accurately and efficiently",
      "Maintain organized office environment and filing systems",
      "Support general office operations and administrative functions",
    ],
    qualifications: [
      "1 to less than 7 months of administrative experience",
      "Secondary (high) school graduation certificate required",
      "Experience in general office environment preferred",
      "Proficiency in typing and proofreading skills",
      "Knowledge of computerized filing systems and data entry",
      "Experience with scheduling and appointment coordination",
      "Strong telephone communication and message relay skills",
      "Ability to compile data and prepare meeting minutes",
      "Travel arrangement and reservation experience preferred",
      "Highly organized with attention to detail",
      "Team player with collaborative work approach",
      "Efficient interpersonal skills for greeting visitors and coordinating with team",
      "Ability to work on-site with no remote work options",
      "Proficiency in English for all communication tasks",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/44959897",
  },
  {
    id: "3",
    role: "Long Haul Truck Driver",
    company_name: "BIK-KEN TRUCKING LTD",
    company_logo: "/images/creative-studios.jpg",
    location: "Edmonton, AB",
    tags: [
      { name: "Full-time", color: "flutter" },
      { name: "On-site", color: "mobile" },
      { name: "Edmonton, AB", color: "ios" },
      // { name: "Will Train", color: "android" },
    ],
    full_description:
      "BIK-KEN TRUCKING LTD is seeking Long Haul Truck Drivers for our Edmonton location (T6H 2J7). This permanent, full-time position offers $35.40 hourly for 30-40 hours per week with flexible scheduling (early morning, morning, day, evening, night, weekend) starting as soon as possible. No education requirements and we will train the right candidates. Work must be completed at the physical location with no remote work options.",
    responsibilities: [
      "Demonstrate mountain driving expertise for challenging terrain",
      "Arrange travel, related itineraries and make reservations for routes",
      "Load and unload goods safely and efficiently",
      "Obtain special permits and other documents required to transport cargo on international routes",
      "Operate and drive straight or articulated trucks to transport goods and materials",
      "Oversee condition of vehicle and inspect tires, lights, brakes, cold storage and other equipment",
      "Pay and receive payments for goods during delivery and pickup",
      "Perform brake adjustments and basic vehicle maintenance",
      "Perform pre-trip, en route and post-trip inspection and oversee all aspects of vehicle",
      "Receive and relay information to central dispatch for route coordination",
      "Record cargo information, hours of service, distance travelled and fuel consumption",
      "Transport and handle dangerous goods in compliance with regulations",
      "Maintain accurate logbooks and delivery documentation",
      "Ensure compliance with transportation safety regulations",
    ],
    qualifications: [
      "No degree, certificate or diploma required",
      "Will train suitable candidates - no prior experience necessary",
      "Must be willing to learn mountain driving techniques",
      "Ability to obtain special permits for international cargo transport",
      "Physical capability to load and unload goods",
      "Understanding of vehicle inspection and maintenance procedures",
      "Ability to handle payments and financial transactions",
      "Strong communication skills for dispatch coordination",
      "Attention to detail for accurate record keeping",
      "Ability to work flexible schedules including early morning, evening, night, and weekends",
      "Willingness to transport dangerous goods with proper training",
      "Ability to work on-site with extensive travel requirements",
      "Proficiency in English for communication and documentation",
      "Valid driver's license (commercial license training available)",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/44958675",
  },
  {
    id: "4",
    role: "Technical Service Sales Consultant",
    company_name: "Canada Copier Remarketing Corp.",
    company_logo: "/images/company-logo.jpg",
    location: "Mississauga, ON",
    tags: [
      { name: "Full-time", color: "flutter" },
      { name: "On-site", color: "mobile" },
      { name: "Mississauga, ON", color: "ios" },
      { name: "Technical Sales", color: "android" },
    ],
    full_description:
      "Canada Copier Remarketing Corp. is seeking a Technical Service Sales Consultant for our Mississauga, ON location. This green job contributes to positive environmental outcomes and helps Canada achieve its net-zero target. Offering $37.65/hour for 30-35 hours per week with permanent employment, morning shifts starting ASAP. Work must be completed at the physical location with no remote option. Benefits include free parking and other benefits.",
    responsibilities: [
      "Estimate costs of installing equipment for client projects",
      "Oversee the preparation of sales orders and documentation",
      "Promote sales to existing clients and maintain customer relationships",
      "Identify and solicit potential clients for business expansion",
      "Assess client's needs and resources to recommend appropriate goods or services",
      "Conduct sales transactions and process customer orders",
      "Provide input into product design where goods must be tailored to client needs",
      "Consult with clients after sale to provide ongoing technical support",
      "Train customers' staff in the operation and maintenance of equipment",
      "Provide clients with presentations on the benefits and uses of products",
      "Resolve product and service related problems efficiently",
      "Troubleshoot problems related to office/business equipment",
      "Advertise and promote products, sales or services to target markets",
      "Provide exceptional customer service throughout the sales process",
      "Supervise activities of other technical sales specialists as needed",
    ],
    qualifications: [
      "Secondary (high) school graduation certificate or equivalent experience",
      "1 to less than 7 months of experience in technical sales",
      "Hardware and office/business equipment sales experience preferred",
      "Excellent oral communication and efficient interpersonal skills",
      "Client focus with ability to work in fast-paced environment",
      "Team player with positive attitude and ability to work under pressure",
      "English language proficiency required",
      "Ability to work morning shifts and adapt to changing priorities",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/45008019",
  },
  {
    id: "5",
    role: "Digital Communications Specialist",
    company_name: "Andrew Law Office",
    company_logo: "/images/cloudnative.jpg",
    location: "Edmonton, AB",
    tags: [
      { name: "Full-time", color: "flutter" },
      { name: "On-site", color: "mobile" },
      { name: "Communications", color: "ios" },
      { name: "Edmonton, AB", color: "android" },
    ],
    full_description:
      "Andrew Law Office is seeking a Digital Communications Specialist with some duties as an International Relations Specialist for our Edmonton location (7208 suite 75 STREET, T6C 2E7). This permanent, full-time on-site position offers $40.00/hour for 40 hours per week starting as soon as possible. We require 5+ years of experience and a Bachelor's degree or equivalent. Comprehensive benefits include health, dental, vision, financial benefits, and other perks. Work must be completed at the physical location with no remote options.",
    responsibilities: [
      "Prepare written material such as reports, briefs, and website content",
      "Answer written and oral inquiries professionally and promptly",
      "Co-ordinate special publicity events and promotional activities",
      "Develop comprehensive portfolio of marketing materials",
      "Conduct online marketing, E-commerce and website promotions",
      "Develop and implement effective marketing strategies",
      "Create content for interactive and new media platforms",
      "Manage digital media communications and campaigns",
      "Work with product development teams on communication strategies",
      "Maintain attention to detail in all communications materials",
      "Support international relations activities as needed",
      "Utilize various software tools for content creation and management",
      "Coordinate with clients and stakeholders on communication needs",
      "Ensure all communications align with organizational goals and brand standards",
    ],
    qualifications: [
      "5 years or more of experience in digital communications or related field",
      "Bachelor's degree or equivalent experience in communications, marketing, or related field",
      "Proficiency in Microsoft Publisher, MS Office Suite (Excel, PowerPoint, Word, Outlook)",
      "Experience with Adobe Photoshop for graphic design and content creation",
      "Knowledge of spreadsheet and database management systems",
      "Experience in product development and interactive/new media",
      "Specialization in communications and digital media platforms",
      "Excellent oral and written communication skills",
      "Client focus with efficient interpersonal skills",
      "Highly organized with strong attention to detail",
      "Reliability and ability to work in fast-paced environment",
      "Ability to work on-site with no remote work options",
      "Must pass criminal record check for security and safety",
      "Proficiency in English for all communication tasks",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/44935336",
  },
  {
    id: "6",
    role: "Home Support Worker",
    company_name: "PALANDRA",
    company_logo: "/images/company-logo.jpg",
    location: "North York, ON",
    tags: [
      { name: "Full-time", color: "flutter" },
      { name: "On-site", color: "mobile" },
      { name: "North York, ON", color: "ios" },
      { name: "Healthcare", color: "android" },
    ],
    full_description:
      "PALANDRA is seeking a dedicated Home Support Worker for our North York, ON location (M2M 1Y8). This term/contract, full-time on-site position offers $20.00/hour for 40 hours per week starting as soon as possible. We require 1-2 years of experience and a secondary school graduation certificate or equivalent. Work in employer's/client's home with optional live-in accommodation available at no charge. Benefits include parking and other benefits.",
    responsibilities: [
      "Administer bedside and personal care to clients with various needs",
      "Assist clients in water activities and therapeutic exercises (pool)",
      "Assist clients with bathing and other aspects of personal hygiene",
      "Assist in regular exercise programs, including walking and mobility",
      "Feed clients or assist in feeding when needed",
      "Launder clothing and household linens as required",
      "Perform light housekeeping and cleaning duties",
      "Plan therapeutic diets and nutritious menus for clients",
      "Provide companionship and emotional support",
      "Provide comprehensive personal care services",
      "Prepare and serve nutritious meals according to dietary requirements",
      "Cook meals and manage kitchen responsibilities",
      "Work with diverse target audiences including elderly, disabled, and Alzheimer's patients",
      "Maintain client safety and follow care protocols",
    ],
    qualifications: [
      "1 year to less than 2 years of experience in home support or healthcare",
      "Secondary (high) school graduation certificate or equivalent experience",
      "Basic security clearance required for safety protocols",
      "Experience working with elderly clients and persons with disabilities",
      "Knowledge of care for persons with Alzheimer's disease preferred",
      "Punctuality and dependability in client care schedules",
      "Client focus with efficient interpersonal skills",
      "Excellent oral communication for client and family interaction",
      "Flexibility to adapt to varying client needs and schedules",
      "Initiative and good judgement in care situations",
      "Highly organized with attention to care details",
      "Reliability and team player mentality",
      "Patience and honesty in all client interactions",
      "Ability to work on-site in client homes with no remote options",
      "Proficiency in English for communication and documentation",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/45007724",
  },
  {
    id: "7",
    role: "Restaurant Manager",
    company_name: "Paratha Junction Inc",
    company_logo: "/images/company-logo.jpg",
    location: "Windsor, ON",
    tags: [
      { name: "Full-time", color: "flutter" },
      { name: "On-site", color: "mobile" },
      { name: "Windsor, ON", color: "ios" },
      { name: "Management", color: "android" },
    ],
    full_description:
      "Paratha Junction Inc is seeking an experienced Restaurant Manager for our Windsor, ON location (992 University Ave West, N9A 5S2). This permanent, full-time on-site position offers $59,600 annually for 30 hours per week starting as soon as possible. We require 1-2 years of experience and a secondary school graduation certificate. Budgetary responsibility of $0-$100,000. Must be bondable with excellent leadership skills to supervise 3-4 staff members. Public transportation available.",
    responsibilities: [
      "Analyze budget to boost and maintain the restaurant's profits",
      "Evaluate daily operations and implement improvements",
      "Modify food preparation methods and menu prices according to restaurant budget",
      "Monitor revenues to determine labour cost and optimize profitability",
      "Monitor staff performance and provide feedback for improvement",
      "Plan and organize daily operations to ensure smooth restaurant functionality",
      "Recruit staff and conduct hiring processes for restaurant positions",
      "Set staff work schedules to meet operational needs",
      "Supervise staff and provide leadership to team of 3-4 people",
      "Train staff on restaurant procedures, customer service, and food safety",
      "Determine type of services to be offered and implement operational procedures",
      "Balance cash and complete balance sheets, cash reports and related forms",
      "Conduct performance reviews and manage staff development",
      "Cost products and services to maintain profitability",
      "Organize and maintain inventory levels and order supplies",
      "Ensure health and safety regulations are followed at all times",
      "Negotiate arrangements with suppliers for food and other supplies",
      "Negotiate with clients for catering or use of facilities",
      "Participate in marketing plans and implementation strategies",
      "Address customers' complaints or concerns in professional manner",
      "Provide exceptional customer service and manage events",
      "Plan, organize, direct, control and evaluate daily operations",
    ],
    qualifications: [
      "1 year to less than 2 years of restaurant management experience",
      "Secondary (high) school graduation certificate required",
      "Must be bondable for security and safety requirements",
      "Experience with budgetary responsibility up to $100,000",
      "Proven ability to supervise and lead team of 3-4 staff members",
      "Knowledge of food preparation methods and menu pricing",
      "Experience with cash handling, balance sheets, and financial reporting",
      "Understanding of health and safety regulations in food service",
      "Experience with supplier negotiations and inventory management",
      "Customer service and complaint resolution skills",
      "Accurate with attention to detail in all operations",
      "Client focus with dependability and reliability",
      "Efficient interpersonal skills and excellent oral/written communication",
      "Flexibility and ability to multitask in fast-paced environment",
      "Highly organized with ability to work under pressure and tight deadlines",
      "Physical capability for demanding work (sitting, standing, walking)",
      "Team player mentality with leadership capabilities",
      "Ability to work on-site with no remote options",
      "Proficiency in English for all communication and documentation",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/45007347",
  },
  {
    id: "8",
    role: "Hairstylist",
    company_name: "Est-ce qu'on te coiffe?",
    company_logo: "/images/company-logo.jpg",
    location: "Quebec City, QC",
    tags: [
      { name: "Full-time", color: "flutter" },
      { name: "On-site", color: "mobile" },
      { name: "Quebec City, QC", color: "ios" },
      { name: "Beauty & Personal Care", color: "android" },
    ],
    full_description:
      "Est-ce qu'on te coiffe? is seeking a skilled Hairstylist for our Quebec City location (2500 Chemin des Quatres-Bourgeois, G1V 4P9). This permanent, full-time on-site position offers $16.10-$35.00/hour (negotiable) for 37 hours per week with flexible scheduling (morning, day, evening) starting as soon as possible. We require 2-3 years of experience and other trades certificate/diploma or equivalent. French language required. Excellent benefits including commission, bonus, paid training, and team building opportunities.",
    responsibilities: [
      "Advise clients on beauty care treatments and hair maintenance",
      "Cut and trim hair according to client's instructions or preferences",
      "Shampoo customers' hair using appropriate products and techniques",
      "Shave and trim beards and mustaches for male clients",
      "Apply bleach, tints, dyes or rinses to colour, frost or streak hair",
      "Cut, trim, taper, curl, wave, perm and style hair according to latest trends",
      "Suggest hair styles compatible with client's physical features and preferences",
      "Perform various hair colouring techniques including dyes, tints, frosting, and highlights",
      "Maintain clean and organized work station and tools",
      "Provide excellent customer service and build client relationships",
      "Stay updated on current hair trends and styling techniques",
      "Recommend hair care products and treatments to clients",
      "Ensure compliance with health and safety regulations",
      "Manage appointment scheduling and client consultations",
    ],
    qualifications: [
      "2 years to less than 3 years of professional hairstyling experience",
      "Other trades certificate or diploma in hairstyling/cosmetology or equivalent experience",
      "Proficiency in French language for client communication",
      "Expertise in hair colouring techniques including dyes, tints, frosting, and streaking/highlights",
      "Knowledge of various cutting, styling, and chemical treatment procedures",
      "Experience with beard and mustache grooming for male clients",
      "Client focus with efficient interpersonal skills",
      "Excellent oral communication in French",
      "Reliability and professional appearance",
      "Knowledge of beauty care treatments and product recommendations",
      "Ability to work flexible schedules (morning, day, evening shifts)",
      "Understanding of health and safety regulations in salon environment",
      "Ability to work on-site with no remote options",
      "Creative flair and attention to detail in styling",
    ],
    applicationLink: "https://www.jobbank.gc.ca/jobsearch/jobposting/45006940",
  },
];

export default jobs;
